-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 18:31:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flowershop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flowershop` ;

-- -----------------------------------------------------
-- Schema flowershop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flowershop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `flowershop` ;

-- -----------------------------------------------------
-- Table `flowershop`.`flowershop`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowershop`.`flowershop` ;

CREATE TABLE IF NOT EXISTS `flowershop`.`flowershop` (
  `FlowerShop_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`FlowerShop_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `IdFloristeria_UNIQUE` ON `flowershop`.`flowershop` (`FlowerShop_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `flowershop`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowershop`.`products` ;

CREATE TABLE IF NOT EXISTS `flowershop`.`products` (
  `Product_id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Price` DECIMAL(9,2) NOT NULL,
  `Quantity` INT NOT NULL,
  `Type` VARCHAR(100) NOT NULL,
  `FlowerShop` INT NOT NULL,
  `Colour` VARCHAR(45) NULL,
  `Material` VARCHAR(45) NULL,
  `Height` VARCHAR(45) NULL,
  PRIMARY KEY (`Product_id`),
  CONSTRAINT `fk_products_flowershop1`
    FOREIGN KEY (`FlowerShop`)
    REFERENCES `flowershop`.`flowershop` (`FlowerShop_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_products_flowershop1_idx` ON `flowershop`.`products` (`FlowerShop` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `flowershop`.`ticket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowershop`.`ticket` ;

CREATE TABLE IF NOT EXISTS `flowershop`.`ticket` (
  `Ticket_id` INT NOT NULL AUTO_INCREMENT,
  `CreationDate` DATETIME NOT NULL,
  `TotalPrice` DECIMAL(9,2) NOT NULL,
  `FlowerShop` INT NOT NULL,
  PRIMARY KEY (`Ticket_id`),
  CONSTRAINT `fk_ticket_flowershop1`
    FOREIGN KEY (`FlowerShop`)
    REFERENCES `flowershop`.`flowershop` (`FlowerShop_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_ticket_flowershop1_idx` ON `flowershop`.`ticket` (`FlowerShop` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `flowershop`.`ticket_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flowershop`.`ticket_has_products` ;

CREATE TABLE IF NOT EXISTS `flowershop`.`ticket_has_products` (
  `Ticket_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `price` DECIMAL(9,2) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`Ticket_id`, `Product_id`),
  CONSTRAINT `fk_tickethistory_has_products_products1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `flowershop`.`products` (`Product_id`),
  CONSTRAINT `fk_tickethistory_has_products_tickethistory`
    FOREIGN KEY (`Ticket_id`)
    REFERENCES `flowershop`.`ticket` (`Ticket_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_tickethistory_has_products_products1_idx` ON `flowershop`.`ticket_has_products` (`Product_id` ASC) VISIBLE;

CREATE INDEX `fk_tickethistory_has_products_tickethistory_idx` ON `flowershop`.`ticket_has_products` (`Ticket_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
