
DROP DATABASE IF EXISTS `FLOWERSHOP`;
CREATE DATABASE IF NOT EXISTS `FLOWERSHOP`;
USE `FLOWERSHOP`;
CREATE TABLE `FLOWERSHOP`.`FlowerShop` (
  `IdFloristeria` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`IdFloristeria`),
  UNIQUE INDEX `IdFloristeria_UNIQUE` (`IdFloristeria` ASC) VISIBLE);

CREATE TABLE `FLOWERSHOP`.`Products` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NULL,
  `Price` DECIMAL(9,2) NULL,
  `Type` VARCHAR(100) NULL,
  PRIMARY KEY (`idProduct`));
  
CREATE TABLE `FLOWERSHOP`.`Stock` (
  `IdProduct` INT NOT NULL,
  `Qty` INT NULL,
  PRIMARY KEY (`IdProduct`));

CREATE TABLE `FLOWERSHOP`.`TicketProducts` (
  `IdLine` INT NOT NULL AUTO_INCREMENT,
  `IdTicket` INT NOT NULL,
  `IdProdict` INT NOT NULL,
  `Price` DECIMAL(9,2) NOT NULL,
  `Qty` INT NOT NULL,
  PRIMARY KEY (`IdLine`));

CREATE TABLE `FLOWERSHOP`.`TicketHistory` (
  `idTicket` INT NOT NULL AUTO_INCREMENT,
  `CreationDate` DATETIME NOT NULL,
  `TotalPrice` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`idTicket`));
